-- Insert a test manufacturer for development purposes (without user_id since it requires auth.users)
INSERT INTO public.manufacturers (
  id,
  user_id,
  legal_name,
  tax_id,
  registered_brand,
  brand_logo_url,
  country,
  province,
  city,
  address,
  official_website,
  primary_contact_name,
  primary_contact_email,
  primary_contact_phone,
  english_level,
  certifications,
  vacation_dates,
  product_sectors,
  factory_positioning,
  factory_history,
  terms_accepted,
  verified,
  verification_status
) VALUES (
  '00000000-0000-0000-0000-000000000001',
  NULL,
  'Test Manufacturer',
  'TEST123456',
  'TestBrand',
  'https://placeholder.com/logo.png',
  'España',
  'Madrid',
  'Madrid',
  'Calle Test 123',
  'https://test-manufacturer.com',
  'Test Contact',
  'test@test.com',
  '+34600000000',
  'fluido',
  ARRAY['ISO9001'],
  'N/A',
  ARRAY['Electronics'],
  'Testing position',
  'Testing history',
  true,
  true,
  'approved'
) ON CONFLICT (id) DO NOTHING;